### ISSUE TITLE
关于SNSAPI的一点问题

### ISSUE THREAD

**Issue by weixc911214** [hupili/Feedback#1]
你好，我是一名想申请暑期实习的大三学生，看到公告后在github上clone了SNSAPI想进行一下调试，发现有点点瑕疵的地方，希望能反馈给你。
1.在github的安装步骤中，对于导入第三方工具库httplib2等的教程，使用pip的方法目前已经不合适了，貌似是连接的网址不再合适，我自己down了最新的版本不知道是否合适，希望可以review一下。
2.按照SNSAPI的tutorial进行到Step5的时候，使用auth()无法返回true，而是得到一个invalid redirect-url的提示，具体地址如下http://graph.renren.com/oauth/authorize?scope=read_user_status+status_update+publish_comment&state=snsapi%21+Stand+up%2C+Geeks%21+Step+on+the+head+of+those+evil+platforms%21&redirect_uri=http%3A%2F%2Fsnsapi.sinaapp.com%2Fauth.php&response_type=code&client_id=3f15df67d8b649428101878dd66bf109

我分析了一下channel中callback_url，即http://snsapi.sinaapp.com/auth.php。 这个网址时而稳定，可以得到一个确认信息，时而无法连接，不知道在香港会不会遇到这个问题。

由于接触这些的时间不长，没有办法提供更多的feedback，希望您可以尽早帮我解决疑惑，期待您的答复。
我的gmail地址  weixc123@gmail.com

另： 如果方便的话能不能咨询一个问题， 2013的summer intern如果不能有幸被选中，能否自费参加呢，我打算2014年申请美国的MS，但求一份实习经历能够提高自己，方便的话也顺便回复一下吧~ ^_^

**Comment by hupili** [comment]
你好~ 感谢你对snsapi项目和2013暑期项目的兴趣。

关于技术问题，请加入我们的google gruop，

https://groups.google.com/forum/?fromgroups#!forum/snsapi

这样得到的反馈更及时。
- 第一个httplib的问题貌似是最近出的，好像源链接坏了（还是墙了？）。你可以手动下载源码安装。我们之后会进行迁移，去除这个依赖。
- 关于callback url，你在snsapi中配置的需要和在人人开放平台上配置的一样。

（跟进这两个技术问题请移步group吧，也有其他同学一起看。）

自费参加我还不清楚，需要去咨询一下。除了费用问题，你要在hk待两个月的话，签证也是问题。如果有官方的实习需求，在政府那边办签证会比较容易。
